spring:
  application:
    name: "LUIS V2 Backend"
  datasource:
    url: jdbc:postgresql://localhost:5432/forecasts
    username: forecast_user
    password: forecast_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true

luis:
  export-url: "https://app.luis.steiermark.at/luft2/export.php"
  scrape-url: "https://app.luis.steiermark.at/luft2/suche.php"