CREATE TABLE "FORECASTS"
  ("FC_TIMESTAMP" DATE,
   "FC_STATION" VARCHAR(32),
   "FC_COMPONENT" VARCHAR(32),
   "FC_VALUE" VARCHAR(32)
   CONSTRAINT "PK_FORECASTS" PRIMARY KEY ("FC_TIMESTAMP", "FC_COMPONENT")
  );